before_install:
  - npm install -g npm

cache:
  directories:
    - node_modules

env:
  global:
    - secure: "jSjBGEqc1efTK+R5hanlvixDg0lEo6ARvbHDFefUnthC7lkIc1NZ6gAT/cK1DrYv2K5BhVYAUIhHUnfIUQAzyJRciuaghbhRrGiygAqkFNiFm5SMTnbSC3+Skw5ctY/BG1Bg+EktHtY7CSQzTc0msys3StgfyD1ef64+8B10AN3VbMH4b9TepblFDFFpbtiicTSyJNvO66VFcQ3ZfeWQ+ke/QQH8SUEbYwYRFn6fQi69be/3zVb2jb+GINqulej0BJhlL0R2NUDWeVUAMayYxwGNeEm9G7sFjnBHvHb5SIALrxfzvTI+myweey9pavSL6tjLJeM93e5IUw4mBzFXE+6o7zv5F4sTRibLdJsTt5sQHSp79FPbE06hUtJ/410hphvjAKPyVhEfDxXqt308i99CLwGXzNPB1lK7T6jVVOP0CHMelYW5XyiNUhU5AXNsj59VCMNhbAfuHSf3wgsP6+YIgPtQFmhcExUMrQMsQkOeDR5hKVyFC8Hx1oGnwV/USj5YEAcS/VvwAB/vzYv4hs2avki/8LDw/o803Lzay0x1cDCSpmKUT8JMMlJGZbOPqLhhCQrl9BCgBXYGz5RdLYgvB6Q8bunMrtCPHHwUcwBKEmwudb1ZszH1et5HwmvEQ/fjgz3TA4movR1MvuII5Ab2tbcavlVn4IXe3qknmIs="
    - secure: "ydKcQ812zA1oD96ZLQAWI5PzYBjCXSs5w7OI/cARAtw8p+2i6c+0PV7n/HT4fBCblC0FhbWMS1mkMEB/kH6CudCjU/T0QK13W35Gl+aHPs1lma1jZO/gYI2UZoDwq+wI9PNvOaxZktmdoXtqjBj2cluYgql3wO//LGgT0DAfeouGQOw0F/0/MluERdjiP/a2NRws44O03HZcFXoYI3NgQRN8VKMqbdveWDL2vmsfpvPrTv0bKXQmKqIPW9Idv/gzNU4v3UhFRyqGy8M/BwYMxg/vaMJMRPCFUYKFHXoKQtx0ClkzXkZDY0yFIapV3FrCWdqoV2Wr05cSNpW3E+eaTgjavKt1HGQO/FQglPrMAc8bnRw7D9nOIX96gzKCWxpLx7rv0y0WDK3PSba4NAPWA/v9yqHirO6kzBxuaRAIDrPgFdQ3JF/CCYE/NCoS5Etfz1GHpM+d+Q0oeZI/Vpvu9M5h8cp5hHT3qYBgG/wLOHZMzwFBWbenesWyRcMUHCw387os6Lf+Z3sjUSAW6KhgLy7Ez7c5DbdjW+k/+dTICOpUubwjUyQb5cHhrfiablxz/nlPEyWy41Uf/TuKx6YpGBLaqVQ/2d5TpYtg4AUmWdMSjdNt5YzWgBrt6bQsJFavSSgxcmeqnuGcDI1BS/T1QHo7Om9kLN4i2nrfvLUrCik="

language: node_js

node_js:
  - 0.10

script: npm run test:browsers

sudo: false
